apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: nathan.wallace114@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          route53:
            accessKeyIDSecretRef:
              key: access-key-id
              name: route53-credentials-secret
            hostedZoneID: Z06135012KVE9P1H4UWDK
            region: global
            secretAccessKeySecretRef:
              key: secret-access-key
              name: route53-credentials-secret
